[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
test_solana_program = "FSzAQ5gnGcpGTc6HoPb28JMBnVWyZ7Uj1NXZ2zrwYLyh"

[[test.genesis]]
address = "22zoJMtdu4tQc2PzL74ZUT7FrwgB1Udec8DdW4yw4BdG"
program = "programs/sas.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
